import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Name } from "@/components/Name";
import { UserProfile } from "@/components/UserProfile";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between border border-b">
          <Name />
          <UserProfile />
        </div>
        {children}
      </body>
    </html>
  );
}
